### ISSUE TITLE
Using RepositoryKit with Realm?

### ISSUE THREAD

**Issue by marbetschar** [LucianoPolit/RepositoryKit#5]
I'd love to use RepositoryKit with Realm as local storage instead of CoreData. The main reason for this is, I do not have any experience with CoreData yet, but I already played with Realm - and it just works ;)

I noticed the [`Storage`](https://github.com/LucianoPolit/RepositoryKit/blob/develop/Source/Core/Storage.swift) protocol is bound to `CoreData`. Now I'm wondering if it is possible as of now to use RepositoryKit with a different local storage than `CoreData`? Or is this something which should be implemented first, before Realm may come into play?

**Comment by LucianoPolit** [comment]
Yeah, I also thought about it. If I'm not wrong, it should be something really really easy! You just need a new `RealmRepository`. Just let me finish on what I'm on now and I'll give you an example 😄 

Also, I guess I'll add an add-on with that new repository.

**Comment by marbetschar** [comment]
Thank you so much, I really appreciate your work!!!

**Comment by LucianoPolit** [comment]
Hey mate, good news! There is a new branch, [realm](https://github.com/LucianoPolit/RepositoryKit/tree/realm), where you can find the new feature. There is a very simple example of how to create the new repository type and how to install it via `Cocoapods` or `Carthage` (on the README).

I'm going to keep it in a new branch because I do not want to have a dependency to `Realm` on the main branch.

PD: I'm making the tests and documentation right now.

**Comment by LucianoPolit** [comment]
Oh man, I'm sorry to say that I have bad news. I made a `CRUDRealmRepository` that it worked, but the `SynchronizableRepository` does not work because the way that `Realm` update the objects. Right now I have not the time to spend on more changes, but I offer you to fork that branch and update  the repository to make it work.

In case you are interested, you should change the `SynchronizableRepository` file to avoid calling the `storage.update` and make some `realm.write { ... }`.

**Comment by marbetschar** [comment]
@LucianoPolit Ok got it, never mind! Thank you for the work as of now!!
